openapi: 3.0.0
info:
  title: ' Convert Page JSON to Email JSON'
  description: Convert a page JSON template to an email JSON template, and ensure
    compatibility throughout the conversion process by removing or adjusting unsupported
    blocks.
  version: 1.0.0
servers:
- url: https://api.getbee.io
  description: Base URL for the API
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Enter Dev Console API Key as Bearer token
paths:
  /v1/{collection}/page-to-email:
    post:
      summary: ' Convert Page JSON to Email JSON'
      description: Convert a page JSON template to an email JSON template, and ensure
        compatibility throughout the conversion process by removing or adjusting unsupported
        blocks.
      security:
      - bearerAuth: []
      parameters:
      - name: collection
        in: path
        required: true
        description: The collection ID or name
        schema:
          type: string
      requestBody:
        required: true
        description: Request body for the endpoint
        content:
          application/json:
            schema:
              type: object
              properties:
                disableHtmlSanitizer:
                  type: integer
                  description: An integer field for disableHtmlSanitizer
                  example: true
                template:
                  type: object
                  description: An object field for template
                  properties:
                    page:
                      type: object
                      description: An object field for page
                      properties:
                        body:
                          type: object
                          description: An object field for body
                          properties:
                            container:
                              type: object
                              description: An object field for container
                              properties:
                                style:
                                  type: object
                                  description: An object field for style
                                  properties:
                                    background-color:
                                      type: string
                                      description: A string field for background-color
                                      example: '#FFFFFF'
                                  example:
                                    background-color: '#FFFFFF'
                              example:
                                style: &id001
                                  background-color: '#FFFFFF'
                            content:
                              type: object
                              description: An object field for content
                              properties:
                                computedStyle:
                                  type: object
                                  description: An object field for computedStyle
                                  properties:
                                    linkColor:
                                      type: string
                                      description: A string field for linkColor
                                      example: '#0068A5'
                                    messageBackgroundColor:
                                      type: string
                                      description: A string field for messageBackgroundColor
                                      example: transparent
                                    messageWidth:
                                      type: string
                                      description: A string field for messageWidth
                                      example: 500px
                                  example:
                                    linkColor: '#0068A5'
                                    messageBackgroundColor: transparent
                                style:
                                  type: object
                                  description: An object field for style
                                  properties:
                                    color:
                                      type: string
                                      description: A string field for color
                                      example: '#000000'
                                    font-family:
                                      type: string
                                      description: A string field for font-family
                                      example: Arial, Helvetica, sans-serif
                                  example:
                                    color: '#000000'
                                    font-family: Arial, Helvetica, sans-serif
                              example:
                                computedStyle: &id002
                                  linkColor: '#0068A5'
                                  messageBackgroundColor: transparent
                                  messageWidth: 500px
                                style: &id003
                                  color: '#000000'
                                  font-family: Arial, Helvetica, sans-serif
                            type:
                              type: string
                              description: A string field for type
                              example: mailup-bee-page-properties
                            webFonts:
                              type: array
                              description: An array of strings for webFonts
                              items:
                                type: string
                              example: []
                          example:
                            container: &id011
                              style: *id001
                            content: &id012
                              computedStyle: *id002
                              style: *id003
                        description:
                          type: string
                          description: A string field for description
                          example: Empty template for BEE
                        rows:
                          type: array
                          description: An array of objects for rows
                          items:
                            type: object
                            properties:
                              columns:
                                type: array
                                description: An array of objects for columns
                                items:
                                  type: object
                                  properties:
                                    grid-columns:
                                      type: integer
                                      description: An integer field for grid-columns
                                      example: 12
                                    modules:
                                      type: array
                                      description: An array of objects for modules
                                      items:
                                        type: object
                                        properties:
                                          type:
                                            type: string
                                            description: A string field for type
                                            example: mailup-bee-newsletter-modules-html
                                          descriptor:
                                            type: object
                                            description: An object field for descriptor
                                            properties:
                                              html:
                                                type: object
                                                description: An object field for html
                                                properties:
                                                  html:
                                                    type: string
                                                    description: A string field for
                                                      html
                                                    example: <div class="our-class"><script>console.log("ok");</script>test
                                                      1</div>
                                                example:
                                                  html: <div class="our-class"><script>console.log("ok");</script>test
                                                    1</div>
                                              style:
                                                type: object
                                                description: An object field for style
                                                properties:
                                                  padding-top:
                                                    type: string
                                                    description: A string field for
                                                      padding-top
                                                    example: 0px
                                                  padding-right:
                                                    type: string
                                                    description: A string field for
                                                      padding-right
                                                    example: 0px
                                                  padding-bottom:
                                                    type: string
                                                    description: A string field for
                                                      padding-bottom
                                                    example: 0px
                                                  padding-left:
                                                    type: string
                                                    description: A string field for
                                                      padding-left
                                                    example: 0px
                                                example:
                                                  padding-top: 0px
                                                  padding-right: 0px
                                              computedStyle:
                                                type: object
                                                description: An object field for computedStyle
                                                properties:
                                                  hideContentOnMobile:
                                                    type: integer
                                                    description: An integer field
                                                      for hideContentOnMobile
                                                    example: false
                                                  hideContentOnDesktop:
                                                    type: integer
                                                    description: An integer field
                                                      for hideContentOnDesktop
                                                    example: false
                                                  hideContentOnAmp:
                                                    type: integer
                                                    description: An integer field
                                                      for hideContentOnAmp
                                                    example: false
                                                  hideContentOnHtml:
                                                    type: integer
                                                    description: An integer field
                                                      for hideContentOnHtml
                                                    example: false
                                                example:
                                                  hideContentOnMobile: false
                                                  hideContentOnDesktop: false
                                            example:
                                              html: &id004
                                                html: <div class="our-class"><script>console.log("ok");</script>test
                                                  1</div>
                                              style: &id005
                                                padding-top: 0px
                                                padding-right: 0px
                                                padding-bottom: 0px
                                                padding-left: 0px
                                          uuid:
                                            type: string
                                            description: A string field for uuid
                                            example: f6c6a079-dd90-4589-8855-93dfdf74461d
                                          locked:
                                            type: integer
                                            description: An integer field for locked
                                            example: false
                                      example:
                                      - &id006
                                        type: mailup-bee-newsletter-modules-html
                                        descriptor:
                                          html: *id004
                                          style: *id005
                                          computedStyle:
                                            hideContentOnMobile: false
                                            hideContentOnDesktop: false
                                            hideContentOnAmp: false
                                            hideContentOnHtml: false
                                        uuid: f6c6a079-dd90-4589-8855-93dfdf74461d
                                        locked: false
                                    style:
                                      type: object
                                      description: An object field for style
                                      properties:
                                        background-color:
                                          type: string
                                          description: A string field for background-color
                                          example: transparent
                                        border-bottom:
                                          type: string
                                          description: A string field for border-bottom
                                          example: 0px solid transparent
                                        border-left:
                                          type: string
                                          description: A string field for border-left
                                          example: 0px solid transparent
                                        border-right:
                                          type: string
                                          description: A string field for border-right
                                          example: 0px solid transparent
                                        border-top:
                                          type: string
                                          description: A string field for border-top
                                          example: 0px solid transparent
                                        padding-bottom:
                                          type: string
                                          description: A string field for padding-bottom
                                          example: 5px
                                        padding-left:
                                          type: string
                                          description: A string field for padding-left
                                          example: 0px
                                        padding-right:
                                          type: string
                                          description: A string field for padding-right
                                          example: 0px
                                        padding-top:
                                          type: string
                                          description: A string field for padding-top
                                          example: 5px
                                      example:
                                        background-color: transparent
                                        border-bottom: 0px solid transparent
                                    uuid:
                                      type: string
                                      description: A string field for uuid
                                      example: cbd74fa2-b853-449e-88b8-f34195441c05
                                example:
                                - &id007
                                  grid-columns: 12
                                  modules:
                                  - *id006
                                  style:
                                    background-color: transparent
                                    border-bottom: 0px solid transparent
                                    border-left: 0px solid transparent
                                    border-right: 0px solid transparent
                                    border-top: 0px solid transparent
                                    padding-bottom: 5px
                                    padding-left: 0px
                                    padding-right: 0px
                                    padding-top: 5px
                                  uuid: cbd74fa2-b853-449e-88b8-f34195441c05
                              container:
                                type: object
                                description: An object field for container
                                properties:
                                  style:
                                    type: object
                                    description: An object field for style
                                    properties:
                                      background-color:
                                        type: string
                                        description: A string field for background-color
                                        example: transparent
                                      background-image:
                                        type: string
                                        description: A string field for background-image
                                        example: none
                                      background-position:
                                        type: string
                                        description: A string field for background-position
                                        example: top left
                                      background-repeat:
                                        type: string
                                        description: A string field for background-repeat
                                        example: no-repeat
                                    example:
                                      background-color: transparent
                                      background-image: none
                                example:
                                  style: &id008
                                    background-color: transparent
                                    background-image: none
                                    background-position: top left
                                    background-repeat: no-repeat
                              content:
                                type: object
                                description: An object field for content
                                properties:
                                  computedStyle:
                                    type: object
                                    description: An object field for computedStyle
                                    properties:
                                      hideContentOnDesktop:
                                        type: integer
                                        description: An integer field for hideContentOnDesktop
                                        example: false
                                      hideContentOnMobile:
                                        type: integer
                                        description: An integer field for hideContentOnMobile
                                        example: false
                                      rowColStackOnMobile:
                                        type: integer
                                        description: An integer field for rowColStackOnMobile
                                        example: true
                                      rowReverseColStackOnMobile:
                                        type: integer
                                        description: An integer field for rowReverseColStackOnMobile
                                        example: false
                                      verticalAlign:
                                        type: string
                                        description: A string field for verticalAlign
                                        example: top
                                    example:
                                      hideContentOnDesktop: false
                                      hideContentOnMobile: false
                                  style:
                                    type: object
                                    description: An object field for style
                                    properties:
                                      background-color:
                                        type: string
                                        description: A string field for background-color
                                        example: transparent
                                      background-image:
                                        type: string
                                        description: A string field for background-image
                                        example: none
                                      background-position:
                                        type: string
                                        description: A string field for background-position
                                        example: top left
                                      background-repeat:
                                        type: string
                                        description: A string field for background-repeat
                                        example: no-repeat
                                      color:
                                        type: string
                                        description: A string field for color
                                        example: '#000000'
                                      width:
                                        type: string
                                        description: A string field for width
                                        example: 500px
                                    example:
                                      background-color: transparent
                                      background-image: none
                                example:
                                  computedStyle: &id009
                                    hideContentOnDesktop: false
                                    hideContentOnMobile: false
                                    rowColStackOnMobile: true
                                    rowReverseColStackOnMobile: false
                                    verticalAlign: top
                                  style: &id010
                                    background-color: transparent
                                    background-image: none
                                    background-position: top left
                                    background-repeat: no-repeat
                                    color: '#000000'
                                    width: 500px
                              empty:
                                type: integer
                                description: An integer field for empty
                                example: false
                              locked:
                                type: integer
                                description: An integer field for locked
                                example: false
                              synced:
                                type: integer
                                description: An integer field for synced
                                example: false
                              type:
                                type: string
                                description: A string field for type
                                example: row-1-columns-12
                              uuid:
                                type: string
                                description: A string field for uuid
                                example: d0a914f7-7212-41c6-9372-c954886e6bd4
                          example:
                          - &id014
                            columns:
                            - *id007
                            - grid-columns: 12
                              modules:
                              - type: mailup-bee-newsletter-modules-html
                                descriptor:
                                  html:
                                    html: <div class="our-class"><script>console.log("ok");</script>test
                                      2</div>
                                  style:
                                    padding-top: 0px
                                    padding-right: 0px
                                    padding-bottom: 0px
                                    padding-left: 0px
                                  computedStyle:
                                    hideContentOnMobile: false
                                    hideContentOnDesktop: false
                                    hideContentOnAmp: false
                                    hideContentOnHtml: false
                                uuid: f6c6a079-dd90-4589-8855-93dfdf74461d
                                locked: false
                              style:
                                background-color: transparent
                                border-bottom: 0px solid transparent
                                border-left: 0px solid transparent
                                border-right: 0px solid transparent
                                border-top: 0px solid transparent
                                padding-bottom: 5px
                                padding-left: 0px
                                padding-right: 0px
                                padding-top: 5px
                              uuid: cbd74fa2-b853-449e-88b8-f34195441c05
                            container:
                              style: *id008
                            content:
                              computedStyle: *id009
                              style: *id010
                            empty: false
                            locked: false
                            synced: false
                            type: row-1-columns-12
                            uuid: d0a914f7-7212-41c6-9372-c954886e6bd4
                        template:
                          type: object
                          description: An object field for template
                          properties:
                            name:
                              type: string
                              description: A string field for name
                              example: template-base
                            type:
                              type: string
                              description: A string field for type
                              example: basic
                            version:
                              type: string
                              description: A string field for version
                              example: 2.0.0
                          example:
                            name: template-base
                            type: basic
                        title:
                          type: string
                          description: A string field for title
                          example: Empty Template
                      example:
                        body: &id013
                          container: *id011
                          content: *id012
                          type: mailup-bee-page-properties
                          webFonts: []
                        description: Empty template for BEE
                  example:
                    page: &id015
                      body: *id013
                      description: Empty template for BEE
                      rows:
                      - *id014
                      template:
                        name: template-base
                        type: basic
                        version: 2.0.0
                      title: Empty Template
              example:
                disableHtmlSanitizer: true
                template:
                  page: *id015
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
                example:
                  message: Success
        '400':
          description: Bad request. The request could not be understood or was missing
            required parameters.
        '401':
          description: Unauthorized. Authentication is required and has failed or
            has not been provided.
        '403':
          description: Forbidden. The request was valid, but the server is refusing
            action.
        '500':
          description: Internal Server Error. An unexpected condition was encountered.